### ISSUE TITLE
from models.mynet.BSINet import MyNet这句中的MyNet不存在，BSINet.py中没有MyNet类

### ISSUE THREAD

**Issue by zzjdsy** [JackLiu-97/BGINet#3]

**Comment by JackLiu-97** [comment]
将BSINet修改为 MyNet再试试，代码中的BSINet和MyNet是一个网络，统一一下命名即可。

**Comment by zzjdsy** [comment]
您好，我已经将BSINet.py重命名为mynet.py，然后将所有文件中的BSINet模块修改命名为MyNet模块，最后在demo.py中运行GZ.pth这个模型进行测试，但是出现了如上图所示的报错信息，我尝试按照提示信息进行修改但是没有成功

&nbsp;


周子君
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月30日(星期六) 中午11:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JackLiu-97/BSINet] from models.mynet.BSINet import MyNet这句中的MyNet不存在，BSINet.py中没有MyNet类 (Issue #3)














 
Closed #3 as completed.

**Comment by JackLiu-97** [comment]
你好，我这里看不见你发的图片，可以直接发一下报错信息吗
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月2日 15:16 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
State ***@***.***> |
| 主题 | Re: [JackLiu-97/BSINet] from models.mynet.BSINet import MyNet这句中的MyNet不存在，BSINet.py中没有MyNet类 (Issue #3) |
您好，我已经将BSINet.py重命名为mynet.py，然后将所有文件中的BSINet模块修改命名为MyNet模块，最后在demo.py中运行GZ.pth这个模型进行测试，但是出现了如上图所示的报错信息，我尝试按照提示信息进行修改但是没有成功

&nbsp;


周子君
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;;
发送时间: 2024年11月30日(星期六) 中午11:28
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;; ***@***.***&gt;;
主题: Re: [JackLiu-97/BSINet] from models.mynet.BSINet import MyNet这句中的MyNet不存在，BSINet.py中没有MyNet类 (Issue #3)















Closed #3 as completed.

**Comment by zzjdsy** [comment]
报错信息在demo.py文件的第52行：
Exception has occurred: ModuleNotFoundError






No module named 'models.MGL'
  File "/data/boweiy/BSINet/demo.py", line 52, in <module&gt;     weights_dict = torch.load(args.ckpt_url, map_location=torch.device('cuda')) ModuleNotFoundError: No module named 'models.MGL'
&nbsp;


周子君
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月2日(星期一) 下午3:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JackLiu-97/BSINet] from models.mynet.BSINet import MyNet这句中的MyNet不存在，BSINet.py中没有MyNet类 (Issue #3)














 
 
 你好，我这里看不见你发的图片，可以直接发一下报错信息吗
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&gt; |
 | 发送日期 | 2024年12月2日 15:16 |
 | 收件人 | ***@***.***&gt; |
 | 抄送人 | ***@***.***&gt;,
 State ***@***.***&gt; |
 | 主题 | Re: [JackLiu-97/BSINet] from models.mynet.BSINet import MyNet这句中的MyNet不存在，BSINet.py中没有MyNet类 (Issue #3) |
 您好，我已经将BSINet.py重命名为mynet.py，然后将所有文件中的BSINet模块修改命名为MyNet模块，最后在demo.py中运行GZ.pth这个模型进行测试，但是出现了如上图所示的报错信息，我尝试按照提示信息进行修改但是没有成功
 
 &amp;nbsp;
 
 
 周子君
 ***@***.***
 
 
 
 &amp;nbsp;
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人: ***@***.***&amp;gt;;
 发送时间: 2024年11月30日(星期六) 中午11:28
 收件人: ***@***.***&amp;gt;;
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;
 主题: Re: [JackLiu-97/BSINet] from models.mynet.BSINet import MyNet这句中的MyNet不存在，BSINet.py中没有MyNet类 (Issue #3)
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 Closed #3 as completed.

**Comment by JackLiu-97** [comment]
我刚才试了一下代码，可能是在我上传代码文件时修改了文件的目录结构，导致权重无法正确加载了，具体目录结构我也记不清了。你可以使用此代码重新进行训练，训练代码正常的。


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月2日 15:40 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
State ***@***.***> |
| 主题 | Re: [JackLiu-97/BSINet] from models.mynet.BSINet import MyNet这句中的MyNet不存在，BSINet.py中没有MyNet类 (Issue #3) |
报错信息在demo.py文件的第52行：
Exception has occurred: ModuleNotFoundError






No module named 'models.MGL'
File "/data/boweiy/BSINet/demo.py", line 52, in <module&gt; weights_dict = torch.load(args.ckpt_url, map_location=torch.device('cuda')) ModuleNotFoundError: No module named 'models.MGL'
&nbsp;


周子君
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;;
发送时间: 2024年12月2日(星期一) 下午3:19
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;; ***@***.***&gt;;
主题: Re: [JackLiu-97/BSINet] from models.mynet.BSINet import MyNet这句中的MyNet不存在，BSINet.py中没有MyNet类 (Issue #3)
















你好，我这里看不见你发的图片，可以直接发一下报错信息吗
---- 回复的原邮件 ----
| 发件人 | ***@***.***&gt; |
| 发送日期 | 2024年12月2日 15:16 |
| 收件人 | ***@***.***&gt; |
| 抄送人 | ***@***.***&gt;,
State ***@***.***&gt; |
| 主题 | Re: [JackLiu-97/BSINet] from models.mynet.BSINet import MyNet这句中的MyNet不存在，BSINet.py中没有MyNet类 (Issue #3) |
您好，我已经将BSINet.py重命名为mynet.py，然后将所有文件中的BSINet模块修改命名为MyNet模块，最后在demo.py中运行GZ.pth这个模型进行测试，但是出现了如上图所示的报错信息，我尝试按照提示信息进行修改但是没有成功

&amp;nbsp;


周子君
***@***.***



&amp;nbsp;




------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
发件人: ***@***.***&amp;gt;;
发送时间: 2024年11月30日(星期六) 中午11:28
收件人: ***@***.***&amp;gt;;
抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;
主题: Re: [JackLiu-97/BSINet] from models.mynet.BSINet import MyNet这句中的MyNet不存在，BSINet.py中没有MyNet类 (Issue #3)















Closed #3 as completed.

**Comment by zzjdsy** [comment]
好的，谢谢，我再尝试尝试Sent from my phone-------- Original message --------From: ChenglongLiu ***@***.***>Date: Mon, Dec 2, 2024, 4:07 PMTo: JackLiu-97/BSINet ***@***.***>Cc: zzjdsy ***@***.***>, Author ***@***.***>Subject: Re: [JackLiu-97/BSINet] from models.mynet.BSINet import MyNet这句中的MyNet不存在，BSINet.py中没有MyNet类 (Issue #3)
我刚才试了一下代码，可能是在我上传代码文件时修改了文件的目录结构，导致权重无法正确加载了，具体目录结构我也记不清了。你可以使用此代码重新进行训练，训练代码正常的。


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月2日 15:40 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
State ***@***.***> |
| 主题 | Re: [JackLiu-97/BSINet] from models.mynet.BSINet import MyNet这句中的MyNet不存在，BSINet.py中没有MyNet类 (Issue #3) |
报错信息在demo.py文件的第52行：
Exception has occurred: ModuleNotFoundError






No module named 'models.MGL'
File "/data/boweiy/BSINet/demo.py", line 52, in <module&gt; weights_dict = torch.load(args.ckpt_url, map_location=torch.device('cuda')) ModuleNotFoundError: No module named 'models.MGL'
&nbsp;


周子君
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;;
发送时间: 2024年12月2日(星期一) 下午3:19
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;; ***@***.***&gt;;
主题: Re: [JackLiu-97/BSINet] from models.mynet.BSINet import MyNet这句中的MyNet不存在，BSINet.py中没有MyNet类 (Issue #3)
















你好，我这里看不见你发的图片，可以直接发一下报错信息吗
---- 回复的原邮件 ----
| 发件人 | ***@***.***&gt; |
| 发送日期 | 2024年12月2日 15:16 |
| 收件人 | ***@***.***&gt; |
| 抄送人 | ***@***.***&gt;,
State ***@***.***&gt; |
| 主题 | Re: [JackLiu-97/BSINet] from models.mynet.BSINet import MyNet这句中的MyNet不存在，BSINet.py中没有MyNet类 (Issue #3) |
您好，我已经将BSINet.py重命名为mynet.py，然后将所有文件中的BSINet模块修改命名为MyNet模块，最后在demo.py中运行GZ.pth这个模型进行测试，但是出现了如上图所示的报错信息，我尝试按照提示信息进行修改但是没有成功

&amp;nbsp;


周子君
***@***.***



&amp;nbsp;




------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
发件人: ***@***.***&amp;gt;;
发送时间: 2024年11月30日(星期六) 中午11:28
收件人: ***@***.***&amp;gt;;
抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;
主题: Re: [JackLiu-97/BSINet] from models.mynet.BSINet import MyNet这句中的MyNet不存在，BSINet.py中没有MyNet类 (Issue #3)















Closed #3 as completed.
